### ISSUE TITLE
Background task support

### ISSUE THREAD

**Issue by janosdebugs** [arcalot/arcaflow-plugin-sdk-python#26]
We should support plugins that execute tasks in the background and stop them later. This is useful in cases like running uperf, where a server needs to be started, then other tasks need to be executed, and then cleaned up later.

This could be achieved, by giving the plugin the option to declare a "cleanup" function in the `@plugin.step` declaration, which would be passed the output ID and output data from the step itself. The cleanup step has no option to return any data itself.

## Standalone operation

When running a plugin as a standalone, the starting step would be run, and the cleanup step would be run immediately afterwards. Alternatively, a command-line flag could be passed to keep the service running for a specified amount of time, or indefinitely. If a SIGINT or SIGTERM is received, the cleanup function should be called and the plugin stopped gracefully.

## Engine operation (ATP)

When a plugin is executed in the engine, the cleanup steps are executed in reverse order as they have been started at the end of the current workflow. After executing the step, the SDK needs to wait until it receives a signal. When a SIGINT or SIGTERM is received, the SDK needs to call the cleanup function to let the plugin cleanup any background tasks that are running.

**Comment by dustinblack** [comment]
Superseded by https://github.com/arcalot/arcalot-round-table/blob/signals/art-decisions/proposals/2022-11-20-arcaflow-signals.md
