### ISSUE TITLE
Type support: generic types

### ISSUE THREAD

**Issue by ghost** [arcalot/arcaflow-plugin-sdk-python#37]
## Please describe what you would like to see in this project

Some tasks require a step to be able to accept any, or almost any input. We need a way to support generic types without sacrificing type checking.

Possible solutions for inputs:

- A step may accept any input, disabling type checking in the process.
- The user must manually declare the input and output for steps that can deal with any kind of data
- The step has a two-stage process where first you must declare some parameters statically in the workflow, and the step then forms a schema
- The step will gain an opportunity if it can accept the give input schema
- ?

Possible solutions for outputs:

- A user must manually declare the output schema
- The step may provide its schema based on the database schema
- ?

**Comment by dustinblack** [comment]
Is this resolved by #71?
