### ISSUE TITLE
Release SDK API docs

### ISSUE THREAD

**Issue by janosdebugs** [arcalot/arcaflow-plugin-sdk-python#53]
@sandrobonazzola has added a workflow to generate API docs using Sphinx, but we don't have a way to release these to GitHub Actions. We need a workflow that does this, either on a subpath under arcalot.io, or on a separate subdomain.

This action may be of help: https://github.com/actions/upload-pages-artifact

**Comment by sandrobonazzola** [comment]
Published on read the docs at https://arcaflow-plugin-sdk-python.readthedocs.io/en/latest/# ; we need to setup DNS for arcalot website next.

**Comment by sandrobonazzola** [comment]
Documentation is now online at https://python-sdk.flow.arcalot.io/en/latest/
