### ISSUE TITLE
The "any" type should not allow lists with inconsistent types

### ISSUE THREAD

**Issue by dustinblack** [arcalot/arcaflow-plugin-sdk-python#78]
## Please describe what you would like to see in this project

The existing implementation allows for accepting lists that have different data types per list item. This is broadly incompatible with external use cases and generally bad practice. In the current state, an error will not be exposed until a plugin attempts to use the data in an incompatible way, leading to error reporting only to stderr that we don't control directly. If the schema did not support the mixed types, the error would be caught by the SDK and we could provide better feedback to the user.

## Please describe your use case

Given a list like this:
```yaml
list:
  - 1
  - 2
  - string
  - 3
```

I may end up in an error condition with something like elasticsearch, which will set the list type to an `int` based on the first value, and then will choke on the `string` value. I would perfer this error to be caught and handled by the SDK directly.

**Comment by jdowni000** [comment]
PR has been merged
